# Begin Project
project:
  type: website
  pre-render: wget -nc https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-custom.scss
  post-render: rm lmu-osc-custom.scss
# End Project


# Begin Website
website:
  title: "TUTORIAL TITLE HERE"
  page-footer: 
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/REPO-NAME-HERE
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU_OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU_OSC_logo.svg){width="175"}
  
  
  navbar:
    right: 
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/REPO-NAME-HERE
          - text: Report a Bug
            url:  https://github.com/lmu-osc/REPO-NAME-HERE/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "How to Use and Adapt this Guide"
        contents:
          - href: 01-use-and-adapt/use.qmd
            text: "Using this Guide"
          - href: 01-use-and-adapt/adapt.qmd
            text: "Adapting this Guide"
      - section: "Introduction and Guiding Principles"
        contents:
          - href: 02-guiding-principles/os-principles.qmd
            text: "Open Science Principles"
          - href: 02-guiding-principles/lmu-guidelines.qmd
            text: "LMU Guiding Principles"
      - section: "Research Data Management (RDM) Lifecycle"
        contents:
          - href: 03-rdm-cycle/intro.qmd
            text: "Introduction to RDM Lifecycle"
          - text: "Plan & Design"
            href: 03-rdm-cycle/plan-design.qmd
          - text: "Collect & Manage"
            href: 03-rdm-cycle/collect-manage.qmd
          - text: "Analyse & Collaborate"
            href: 03-rdm-cycle/analyse-collaborate.qmd
          - text: "Preserve & Share"
            href: 03-rdm-cycle/preserve-share.qmd
      - section: "Resources"
        contents:
          - href: 04-resources/index.qmd
            text: "Tools and Best Practices"
      - section: "Appendix"
        contents:
          - href: 05-appendix/glossary.qmd
            text: "Glossary"
          - href: 05-appendix/policies.qmd
            text: "Policies and Guidelines"
# End Website


# Begin Format
format:
  html:
    theme: 
      - cosmo
      - lmu-osc-custom.scss
    css: 
      - https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px
    include-in-header:
      - file: matomo-analytics.html
# End Format

# Begin Editor
editor: source
# End Editor
